title: Håkon's tech blog
email: hakon@hokky.org
author: Håkon Andreas Jensen
description: >  # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hakonaj.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hakonaj
github_username:  hakonaj

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
